
spring:
  jpa:
    show-sql: ${COM_HC_DATABASE_SHOW_SQL:false}
    hibernate:
      ddl-auto: update
      #dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    hc:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${COM_HC_DATABASE_URL:jdbc:mysql://localhost:3307/socialmedia}
      username: ${COM_HC_DATABASE_USERNAME:root}
      password: ${COM_HC_DATABASE_PASSWORD:root}
    hikari:
      connection-timeout: 600000
  redis:
    host: ${COM_HC_REDIS_HOST:localhost}
    port: ${COM_HC_REDIS_PORT:6379}
    password: ${COM_HC_REDIS_PASSWORD:}
    database: ${COM_HC_REDIS_DATABASE:1}
  artemis:
    embedded:
      server-id: